Gingko upgrade; typo fixes; `sudo` > `su`; `apt-mark hold`
regisb/openedx-install pull request #19
Opened 2017-12-08 12:21 UTC by SamuelMarks

`git clone -b`; remove pip & setuptools downgrade; "Open edX" => "OpenEdX"

2017-12-08 12:31 UTC, regisb commented
Hi @SamuelMarks, thanks for your PR! Did you test the upgrade from Ficus to Ginkgo? It would be great if it just worked out of the box! (I suspect it does, since I had no issue upgrading the docker containers in https://github.com/regisb/openedx-docker)

But why don't you want to pin `pip` and `setuptools` to a specific version? In the commit that you pointed to, I see that they are pinned to 9.0.1 and 34.0.2, respectively.

Also, it's "Open edX", not "OpenEdx" :-/ See for instance https://open.edx.org/about-open-edx

2017-12-08 12:32 UTC, SamuelMarks commented
Yeah I tested and got no issues. Still need to test with the pip and setuptools downgrade though, but that shouldn't matter because it's already in base.txt

2017-12-11 07:19 UTC, regisb requested changes

2017-12-11 07:19 UTC, regisb commented on README.md
> +    sudo chown edxapp:edxapp /opt/Open edX
I'd rather we did not insert spaces in the install path. Spaces need to be escaped and they make install instructions more complex.

2017-12-11 07:19 UTC, regisb commented on README.md
> +    git clone -b open-release/gingko.master https://github.com/edx/edx-platform.git
s/gingko/ginkgo/

2017-12-11 07:19 UTC, regisb commented on README.md
> +Usually, the lms is configured on the bare domain name ("myOpen edX.com") or  on the `www` subdomain ("www.myOpen edX.com"), while cms typically uses the `studio` subdomain ("studio.myOpen edX.com").
I think you did a global search & replace that went wrong :) The domain names should definitely not contain white space.

2017-12-11 08:33 UTC, SamuelMarks commented
Resolved

2017-12-11 09:11 UTC, regisb commented
Alright, let me test this before we go further.

2017-12-11 09:11 UTC, regisb commented on README.md
> +    sudo apt-mark hold elasticsearch
:+1:

2018-01-07 07:04 UTC, SamuelMarks commented
@regisb Any news on this PR?

2018-01-07 13:58 UTC, regisb commented
@SamuelMarks haven't had time to test it yet! I just returned from holidays and will catch up on PRs/issues soon.

2018-01-20 14:06 UTC, merged

2018-01-20 14:06 UTC, regisb commented
Thanks a lot @SamuelMarks for your work!